### ISSUE TITLE
File 'multicast_proxy/multicast_kernel/rpmbuild_multicast/RPMS/x86_64/multi_client-1.1-1.x86_64.rpm' not exist

### ISSUE THREAD

**Issue by samuel-yin** [aliyun/multicast_proxy#1]
I received an error when trying to build MULTICAST client rpm by cmd `sh tmcc_client_auto_rpm.sh`.
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.AsspjQ (%build)
cp: cannot stat ‘/root/multicast_proxy/multicast_kernel/rpmbuild_multicast/RPMS/x86_64/multi_client-1.1-1.x86_64.rpm’: No such file or directory

It seems the rpm files of both client & server are missing.

**Comment by xinzaitianshan** [comment]
Maybe have some more issues, such as kernel-devel is not installed. Can you give me more info?
