### ISSUE TITLE
kernel-devel-version

### ISSUE THREAD

**Issue by travelliu** [aliyun/multicast_proxy#3]
+ '[' 0 -ne 0 ']'
+ /usr/bin/tar -xf -
+ /usr/bin/bzip2 -dc /tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/SOURCES/multi_server-1.1.tar.bz2
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd multi_server-1.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.SXsUFQ
+ umask 022
+ cd /tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD
+ cd multi_server-1.1
+ export MULTIC_VERSION=1.1
+ MULTIC_VERSION=1.1
+ echo /tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILDROOT/multi_server-1.1-1.x86_64
/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILDROOT/multi_server-1.1-1.x86_64
+ make clean
make -C kmod clean
make[1]: Entering directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/kmod'
rm -rf *.o *.ko* *.symvers *.mod.c .*.cmd *.order .rlqos.* .tmp_versions
make[1]: Leaving directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/kmod'
make -C tools clean
make[1]: Entering directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools'
make -C multi_server_control clean
make[2]: Entering directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools/multi_server_control'
rm -fr *.o multis_admin 
make[2]: Leaving directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools/multi_server_control'
make -C multi_config_control clean
make[2]: Entering directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools/multi_config_control'
rm -fr *.o multis_config_admin 
make[2]: Leaving directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools/multi_config_control'
rm -fr .tmp_versions
make[1]: Leaving directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/tools'
rm -fr .tmp_versions
+ make
make -C kmod
make[1]: Entering directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/kmod'
make -C /lib/modules/`uname -r`/build M=/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/kmod modules
make: Entering an unknown directory
make: *** /lib/modules/3.10.0-693.2.2.el7.x86_64/build: No such file or directory.  Stop.
make: Leaving an unknown directory
make[1]: *** [default] Error 2
make[1]: Leaving directory `/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/BUILD/multi_server-1.1/kmod'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.SXsUFQ (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.SXsUFQ (%build)
cp: cannot stat ‘/tmp/multicast_proxy-master/multicast_kernel/rpmbuild_multicast/RPMS/x86_64/multi_server-1.1-1.x86_64.rpm’: No such file or directory

[root@rac02 multicast_kernel]# uname -a
Linux rac02 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@rac02 multicast_kernel]# rpm -qa |grep kernel-devel
kernel-devel-3.10.0-957.21.2.el7.x86_64

[root@rac02 multicast_kernel]# yum install kernel-devel-3.10.0-693*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package kernel-devel-3.10.0-693* available.
Error: Nothing to do

**Comment by xinzaitianshan** [comment]
make: *** /lib/modules/3.10.0-693.2.2.el7.x86_64/build: No such file or directory
#yum install kernel-devel-`uname -r` -y
